# Generated by Django 5.2.4 on 2025-07-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('hospital', 'Hospital Department'), ('maintenance', 'Maintenance Department')], default='hospital', max_length=20),
        ),
    ]
