# Generated by Django 5.2.4 on 2025-07-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_transfers/'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
