# Generated by Django 5.2.4 on 2025-07-19 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='usecase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assetmanagement.usecase'),
        ),
    ]
