# Generated by Django 5.2.4 on 2025-07-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0002_department_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
