# Generated by Django 5.2.4 on 2025-07-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0003_alter_asset_current_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(editable=False, max_length=12, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
