### Profile
GET http://localhost:8000/api/auth/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyOTg5NjQ0LCJpYXQiOjE3NTI5ODYwNDQsImp0aSI6ImRhZmJmNTNlYTVjMjRiOWI5N2ExNzc5YjdjNWRiNjBiIiwidXNlcl9pZCI6MX0.GogaAbYbTi_5xU-WFZ7dMKwzaPuOaBrJfHaJVW5C24Y